// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: spec.proto

package TerraformStation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Terraform command input
type TFCommandInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Command          string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	WorkingDirectory string                 `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	Variables        map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Arguments        []string               `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
	PlanFile         string                 `protobuf:"bytes,5,opt,name=plan_file,json=planFile,proto3" json:"plan_file,omitempty"`
	StateFile        string                 `protobuf:"bytes,6,opt,name=state_file,json=stateFile,proto3" json:"state_file,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TFCommandInput) Reset() {
	*x = TFCommandInput{}
	mi := &file_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFCommandInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFCommandInput) ProtoMessage() {}

func (x *TFCommandInput) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFCommandInput.ProtoReflect.Descriptor instead.
func (*TFCommandInput) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{0}
}

func (x *TFCommandInput) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TFCommandInput) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *TFCommandInput) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *TFCommandInput) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *TFCommandInput) GetPlanFile() string {
	if x != nil {
		return x.PlanFile
	}
	return ""
}

func (x *TFCommandInput) GetStateFile() string {
	if x != nil {
		return x.StateFile
	}
	return ""
}

// Terraform command result
type TFCommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	CommandId     string                 `protobuf:"bytes,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TFCommandResult) Reset() {
	*x = TFCommandResult{}
	mi := &file_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFCommandResult) ProtoMessage() {}

func (x *TFCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFCommandResult.ProtoReflect.Descriptor instead.
func (*TFCommandResult) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{1}
}

func (x *TFCommandResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TFCommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TFCommandResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TFCommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TFCommandResult) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

func (x *TFCommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// Terraform plan result
type TFPlanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanOutput    string                 `protobuf:"bytes,2,opt,name=plan_output,json=planOutput,proto3" json:"plan_output,omitempty"`
	HasChanges    bool                   `protobuf:"varint,3,opt,name=has_changes,json=hasChanges,proto3" json:"has_changes,omitempty"`
	ResourceCount int32                  `protobuf:"varint,4,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TFPlanResult) Reset() {
	*x = TFPlanResult{}
	mi := &file_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFPlanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFPlanResult) ProtoMessage() {}

func (x *TFPlanResult) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFPlanResult.ProtoReflect.Descriptor instead.
func (*TFPlanResult) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{2}
}

func (x *TFPlanResult) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *TFPlanResult) GetPlanOutput() string {
	if x != nil {
		return x.PlanOutput
	}
	return ""
}

func (x *TFPlanResult) GetHasChanges() bool {
	if x != nil {
		return x.HasChanges
	}
	return false
}

func (x *TFPlanResult) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *TFPlanResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TFPlanResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Terraform apply result
type TFApplyResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApplyId            string                 `protobuf:"bytes,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	ApplyOutput        string                 `protobuf:"bytes,2,opt,name=apply_output,json=applyOutput,proto3" json:"apply_output,omitempty"`
	Success            bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ResourcesAdded     int32                  `protobuf:"varint,4,opt,name=resources_added,json=resourcesAdded,proto3" json:"resources_added,omitempty"`
	ResourcesChanged   int32                  `protobuf:"varint,5,opt,name=resources_changed,json=resourcesChanged,proto3" json:"resources_changed,omitempty"`
	ResourcesDestroyed int32                  `protobuf:"varint,6,opt,name=resources_destroyed,json=resourcesDestroyed,proto3" json:"resources_destroyed,omitempty"`
	ExecutedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TFApplyResult) Reset() {
	*x = TFApplyResult{}
	mi := &file_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFApplyResult) ProtoMessage() {}

func (x *TFApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFApplyResult.ProtoReflect.Descriptor instead.
func (*TFApplyResult) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{3}
}

func (x *TFApplyResult) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

func (x *TFApplyResult) GetApplyOutput() string {
	if x != nil {
		return x.ApplyOutput
	}
	return ""
}

func (x *TFApplyResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TFApplyResult) GetResourcesAdded() int32 {
	if x != nil {
		return x.ResourcesAdded
	}
	return 0
}

func (x *TFApplyResult) GetResourcesChanged() int32 {
	if x != nil {
		return x.ResourcesChanged
	}
	return 0
}

func (x *TFApplyResult) GetResourcesDestroyed() int32 {
	if x != nil {
		return x.ResourcesDestroyed
	}
	return 0
}

func (x *TFApplyResult) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

// Terraform state information
type TFStateInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StateId          string                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	StateFile        string                 `protobuf:"bytes,2,opt,name=state_file,json=stateFile,proto3" json:"state_file,omitempty"`
	ResourceCount    int32                  `protobuf:"varint,3,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	TerraformVersion string                 `protobuf:"bytes,5,opt,name=terraform_version,json=terraformVersion,proto3" json:"terraform_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TFStateInfo) Reset() {
	*x = TFStateInfo{}
	mi := &file_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFStateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFStateInfo) ProtoMessage() {}

func (x *TFStateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFStateInfo.ProtoReflect.Descriptor instead.
func (*TFStateInfo) Descriptor() ([]byte, []int) {
	return file_spec_proto_rawDescGZIP(), []int{4}
}

func (x *TFStateInfo) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *TFStateInfo) GetStateFile() string {
	if x != nil {
		return x.StateFile
	}
	return ""
}

func (x *TFStateInfo) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

func (x *TFStateInfo) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *TFStateInfo) GetTerraformVersion() string {
	if x != nil {
		return x.TerraformVersion
	}
	return ""
}

var File_spec_proto protoreflect.FileDescriptor

const file_spec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"spec.proto\x12\x10TerraformStation\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x02\n" +
	"\x0eTFCommandInput\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\x12M\n" +
	"\tvariables\x18\x03 \x03(\v2/.TerraformStation.TFCommandInput.VariablesEntryR\tvariables\x12\x1c\n" +
	"\targuments\x18\x04 \x03(\tR\targuments\x12\x1b\n" +
	"\tplan_file\x18\x05 \x01(\tR\bplanFile\x12\x1d\n" +
	"\n" +
	"state_file\x18\x06 \x01(\tR\tstateFile\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x01\n" +
	"\x0fTFCommandResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12;\n" +
	"\vexecuted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\x12\x1d\n" +
	"\n" +
	"command_id\x18\x06 \x01(\tR\tcommandId\"\xe3\x01\n" +
	"\fTFPlanResult\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x1f\n" +
	"\vplan_output\x18\x02 \x01(\tR\n" +
	"planOutput\x12\x1f\n" +
	"\vhas_changes\x18\x03 \x01(\bR\n" +
	"hasChanges\x12%\n" +
	"\x0eresource_count\x18\x04 \x01(\x05R\rresourceCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xab\x02\n" +
	"\rTFApplyResult\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\tR\aapplyId\x12!\n" +
	"\fapply_output\x18\x02 \x01(\tR\vapplyOutput\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12'\n" +
	"\x0fresources_added\x18\x04 \x01(\x05R\x0eresourcesAdded\x12+\n" +
	"\x11resources_changed\x18\x05 \x01(\x05R\x10resourcesChanged\x12/\n" +
	"\x13resources_destroyed\x18\x06 \x01(\x05R\x12resourcesDestroyed\x12;\n" +
	"\vexecuted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\"\xda\x01\n" +
	"\vTFStateInfo\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\tR\astateId\x12\x1d\n" +
	"\n" +
	"state_file\x18\x02 \x01(\tR\tstateFile\x12%\n" +
	"\x0eresource_count\x18\x03 \x01(\x05R\rresourceCount\x12=\n" +
	"\flast_updated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12+\n" +
	"\x11terraform_version\x18\x05 \x01(\tR\x10terraformVersion2\xf3\x03\n" +
	"\x17TerraformStationService\x12P\n" +
	"\tTFCommand\x12 .TerraformStation.TFCommandInput\x1a!.TerraformStation.TFCommandResult\x12J\n" +
	"\x06TFPlan\x12 .TerraformStation.TFCommandInput\x1a\x1e.TerraformStation.TFPlanResult\x12L\n" +
	"\aTFApply\x12 .TerraformStation.TFCommandInput\x1a\x1f.TerraformStation.TFApplyResult\x12M\n" +
	"\x06TFInit\x12 .TerraformStation.TFCommandInput\x1a!.TerraformStation.TFCommandResult\x12Q\n" +
	"\n" +
	"TFValidate\x12 .TerraformStation.TFCommandInput\x1a!.TerraformStation.TFCommandResult\x12J\n" +
	"\aTFState\x12 .TerraformStation.TFCommandInput\x1a\x1d.TerraformStation.TFStateInfoB(Z&github.com/ForestMars/TerraformStationb\x06proto3"

var (
	file_spec_proto_rawDescOnce sync.Once
	file_spec_proto_rawDescData []byte
)

func file_spec_proto_rawDescGZIP() []byte {
	file_spec_proto_rawDescOnce.Do(func() {
		file_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_proto_rawDesc), len(file_spec_proto_rawDesc)))
	})
	return file_spec_proto_rawDescData
}

var file_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_spec_proto_goTypes = []any{
	(*TFCommandInput)(nil),        // 0: TerraformStation.TFCommandInput
	(*TFCommandResult)(nil),       // 1: TerraformStation.TFCommandResult
	(*TFPlanResult)(nil),          // 2: TerraformStation.TFPlanResult
	(*TFApplyResult)(nil),         // 3: TerraformStation.TFApplyResult
	(*TFStateInfo)(nil),           // 4: TerraformStation.TFStateInfo
	nil,                           // 5: TerraformStation.TFCommandInput.VariablesEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_spec_proto_depIdxs = []int32{
	5,  // 0: TerraformStation.TFCommandInput.variables:type_name -> TerraformStation.TFCommandInput.VariablesEntry
	6,  // 1: TerraformStation.TFCommandResult.executed_at:type_name -> google.protobuf.Timestamp
	6,  // 2: TerraformStation.TFPlanResult.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: TerraformStation.TFApplyResult.executed_at:type_name -> google.protobuf.Timestamp
	6,  // 4: TerraformStation.TFStateInfo.last_updated:type_name -> google.protobuf.Timestamp
	0,  // 5: TerraformStation.TerraformStationService.TFCommand:input_type -> TerraformStation.TFCommandInput
	0,  // 6: TerraformStation.TerraformStationService.TFPlan:input_type -> TerraformStation.TFCommandInput
	0,  // 7: TerraformStation.TerraformStationService.TFApply:input_type -> TerraformStation.TFCommandInput
	0,  // 8: TerraformStation.TerraformStationService.TFInit:input_type -> TerraformStation.TFCommandInput
	0,  // 9: TerraformStation.TerraformStationService.TFValidate:input_type -> TerraformStation.TFCommandInput
	0,  // 10: TerraformStation.TerraformStationService.TFState:input_type -> TerraformStation.TFCommandInput
	1,  // 11: TerraformStation.TerraformStationService.TFCommand:output_type -> TerraformStation.TFCommandResult
	2,  // 12: TerraformStation.TerraformStationService.TFPlan:output_type -> TerraformStation.TFPlanResult
	3,  // 13: TerraformStation.TerraformStationService.TFApply:output_type -> TerraformStation.TFApplyResult
	1,  // 14: TerraformStation.TerraformStationService.TFInit:output_type -> TerraformStation.TFCommandResult
	1,  // 15: TerraformStation.TerraformStationService.TFValidate:output_type -> TerraformStation.TFCommandResult
	4,  // 16: TerraformStation.TerraformStationService.TFState:output_type -> TerraformStation.TFStateInfo
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_spec_proto_init() }
func file_spec_proto_init() {
	if File_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_proto_rawDesc), len(file_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spec_proto_goTypes,
		DependencyIndexes: file_spec_proto_depIdxs,
		MessageInfos:      file_spec_proto_msgTypes,
	}.Build()
	File_spec_proto = out.File
	file_spec_proto_goTypes = nil
	file_spec_proto_depIdxs = nil
}
