// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spec.proto

package TerraformStation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TFCommandInput struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TFCommandInput) Reset()         { *m = TFCommandInput{} }
func (m *TFCommandInput) String() string { return proto.CompactTextString(m) }
func (*TFCommandInput) ProtoMessage()    {}
func (*TFCommandInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_d8f3c8df0d901829, []int{0}
}
func (m *TFCommandInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFCommandInput.Unmarshal(m, b)
}
func (m *TFCommandInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFCommandInput.Marshal(b, m, deterministic)
}
func (dst *TFCommandInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFCommandInput.Merge(dst, src)
}
func (m *TFCommandInput) XXX_Size() int {
	return xxx_messageInfo_TFCommandInput.Size(m)
}
func (m *TFCommandInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TFCommandInput.DiscardUnknown(m)
}

var xxx_messageInfo_TFCommandInput proto.InternalMessageInfo

func (m *TFCommandInput) GetCommand() string {
	if m != nil {
		return m.Result // 
	}
	return ""
}

type TFCommandResult struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TFCommandResult) Reset()         { *m = TFCommandResult{} }
func (m *TFCommandResult) String() string { return proto.CompactTextString(m) }
func (*TFCommandResult) ProtoMessage()    {}
func (*TFCommandResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_spec_d8f3c8df0d901829, []int{1}
}
func (m *TFCommandResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFCommandResult.Unmarshal(m, b)
}
func (m *TFCommandResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFCommandResult.Marshal(b, m, deterministic)
}
func (dst *TFCommandResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFCommandResult.Merge(dst, src)
}
func (m *TFCommandResult) XXX_Size() int {
	return xxx_messageInfo_TFCommandResult.Size(m)
}
func (m *TFCommandResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TFCommandResult.DiscardUnknown(m)
}

var xxx_messageInfo_TFCommandResult proto.InternalMessageInfo

func (m *TFCommandResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*TFCommandInput)(nil), "TerraformStation.TFCommandInput")
	proto.RegisterType((*TFCommandResult)(nil), "TerraformStation.TFCommandResult")
}

func init() { proto.RegisterFile("spec.proto", fileDescriptor_spec_d8f3c8df0d901829) }

var fileDescriptor_spec_d8f3c8df0d901829 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2e, 0x48, 0x4d,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x49, 0xcd, 0x2d, 0xc8, 0x49, 0x2c, 0x49,
	0x55, 0x52, 0xe5, 0xe2, 0x0d, 0x4e, 0xac, 0xf4, 0x48, 0xcd, 0xc9, 0xc9, 0xf7, 0xcc, 0x2b, 0x28,
	0x2d, 0x11, 0x12, 0xe1, 0x62, 0xcd, 0x00, 0xf1, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20,
	0x1c, 0x25, 0x0d, 0x2e, 0x3e, 0x98, 0xb2, 0xa0, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0x21, 0x31, 0x2e,
	0xb6, 0x22, 0x30, 0x0b, 0xaa, 0x10, 0xca, 0x4b, 0x62, 0x03, 0xdb, 0x60, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x41, 0x14, 0x35, 0x8d, 0x6f, 0x00, 0x00, 0x00,
}
